# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex

#automatic_scaling:
  #max_num_instances: 1

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"

network:
  session_affinity: true

env_variables:
  spring_profiles_active: "dev"
  SP_DS_UR: $SP_DS_UR
  SP_DS_UN: $SP_DS_UN
  SP_DS_PW: $SP_DS_PW