server:
  port: 8081
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example: DEBUG

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: username
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: dev

---

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
  config:
    activate:
      on-profile: prod