INSERT INTO player (
  id,
  background_music,
  email,
  password,
  points,
  profile_picture,
  status,
  token,
  username,
  rank
  )

VALUES (0, false, 'singleton@singleton.ch', 'lsd2jf$-q5wfead$nsk234r$f4hasd', 0, 'singleton', 0, 'ee763d2b-b89b-426b-9e36-72b995bef822', 'singletonUser',  9999);

INSERT INTO image_question (
  template_image_question_id,
  all_answers,
  api_id,
  correct_answer,
  incorrect_answers,
  question
)

VALUES
  (2, 'Cat,Mouse,Hamster,Dog', 'sjpa0Gg', 'Dog', 'Cat,Mouse,Hamster', 'What kind of animal do you see?'),
  (3, 'Motorcycle,Car,Bicycle,Trike', 'jBtFMql', 'Motorcycle', 'Car,Bicycle,Trike', 'What kind of vehicle do you see?'),
  (4, 'Ferrari,Lamborghini,Aston Martin,Bentley', 'Q1rBT7z', 'Ferrari', 'Lamborghini,Aston Martin,Bentley', 'What kind of car do you see?'),
  (5, 'Beach,Cave,Forest,Harbor', 'Ho2Ni4I', 'Beach', 'Cave,Forest,Harbor', 'Where are you at?'),
  (6, 'Brown Bear,Racoon,Bigfoot,Ape', 'RLcpM4K', 'Brown Bear', 'Ape,Racoon,Bigfoot', 'What animal is hidden in the image?'),
  (7, 'Alligator,Car,Skyline,Dinosaur', 'UBDjXWB', 'Alligator', 'Car,Skyline,Dinosaur', 'What object is hidden in the image?'),
  (8, 'Mars,Jupyter,Neptune,Venus', 'kfjHRvR', 'Mars', 'Venus,Jupyter,Neptune', 'What planet is hidden in the image?'),
  (9, 'Bird,Chipmunk,Rabbit,Weasel', 'oA2709v', 'Bird', 'Chipmunk,Rabbit,Weasel', 'What animal is hidden in the image?'),
  (10, 'Tokyo,Paris,London,Singapore', 'zV0qTkp', 'Tokyo', 'Paris,London,Singapore', 'What city is hidden in the image?'),
  (11, 'Kilimanjaro,Everest,Matterhorn,Mont Blanc', 'V2DBESE', 'Kilimanjaro', 'Everest,Matterhorn,Mont Blanc', 'What mountain is hidden in the image?'),
  (12, 'Dog,Cat,Donkey,Goat', 'AAJc1Rh', 'Donkey', 'Cat,Dog,Goat', 'What kind of animal is hidden in the image?'),
  (13, 'Space Rocket,Candle,Firework,Cigarette', 'hChUSOF', 'Space Rocket', 'Candle,Firework,Cigarette', 'What object is hidden in the image?'),
  (14, 'Beetle,Rhinoceros,Dinosaur,Spider', 'WtgPUUQ', 'Beetle', 'Rhinoceros,Dinosaur,Spider', 'What kind of animal is hidden in the image?'),
  (15, 'Our Sun,Human Cell,Frog Egg,Tennis Ball', 'B3QJiiA', 'Sun', 'Human Cell,Frog Egg,Tennis Ball', 'What object is hidden in the image?'),
  (16, 'Bud Spencer & Terrence Hill,Dumb and Dumber,Laurel & Hardy,Cheeck & Chong', '3XXSb62', 'Bud Spencer & Terrence Hill', 'Dumb and Dumber,Laurel & Hardy,Cheeck & Chong', 'Who are the legends in the photograph?'),
  (17, 'Albert Einstein,Hendrik Lorentz,Max Planck,Niels Bohr', 'YrBRqnp', 'Albert Einstein', 'Hendrik Lorentz,Max Planck,Niels Bohr', 'Who is the guy making fun of the paparazzi?'),
  (18, 'Black Hole,Galaxy,Nebula,Star', 'TzZtugJ', 'Black Hole', 'Galaxy,Nebula,Star', 'What object was captured in this awesome image?'),
  (19, 'Rowan Atkinson,George Washington,Louis XIV,Edward the Great', 'il6w7zw', 'Rowan Atkinson', 'George Washington,Louis XIV,Edward the Great', 'Which famous person shows her face in the painting?'),
  (20, 'Fox,Sea lion,Cat,Dog', 'amckVul', 'Cat', 'Fox,Sea lion,Dog', 'Who is the impostor?'),
  (21, 'Bug,Spider,Butterfly,Seahorse', 'Sm1f3Np', 'Seahorse', 'Bug,Spider,Butterfly', 'What animal is hidden in the image?'),
  (22, 'Butterfly,Plane,Sparrow,Hummingbird', 'XbS348E', 'Hummingbird', 'Butterfly,Plane,Sparrow', 'What object was captured in this image?'),
  (23, 'Florida,Munich,Lisbon,Cape Town', 'qGzjZfD', 'Cape Town', 'Florida,Munich,Lisbon', 'What city is hidden in the image?'),
  (24, 'Jack Nicholson,Sean Penn,Clint Eastwood,John Lennon', '2I2KdXG', 'John Lennon', 'Jack Nicholson,Sean Penn,Clint Eastwood', 'Who is in this picture?'),
  (25, 'Dolphin,Flying Fish,Jet Ski,Humpback whale', 'tUza1OK', 'Humpback Whale', 'Dolphin,Flying Fish,Jet Ski', 'Who is flying in this image?'),
  (26, 'Cabin cruiser,Galley,Ferry,Bow rider', '9JkHXb9', 'Bow rider', 'Cabin cruiser,Galley,Ferry', 'What kind of boat type is in the image?'),
  (27, 'Cabriolet,SUV,Limousine,Coupe', 'eAhl2LC', 'Coupe', 'Cabriolet,SUV,Limousine', 'What is the design of the car in the picture?'),
  (28, 'Spiderman,Thor,Ironman,Captain America', 'KEfW1tG', 'Captain America', 'Spiderman,Thor,Ironman', 'What marvel character is in the picture?'),
  (29, 'Friends,Modern Family,Suits,The Office', 'tphNbfC', 'The Office', 'Friends,Modern Family,Suits', 'In which TV series does this picture occur?'),
  (30, 'New York,London,Zurich,Tokyo', 'AjybU6j', 'Tokyo', 'New York,London,Zurich', 'In which city is this picture taken?'),
  (31, 'Hong Kong Park,Park Guell,Djurgarden,Central Park', 'cvyMf0E', 'Central Park', 'Hong Kong Park,Park Guell,Djurgarden', 'How is this park called?'),
  (32, 'Antoni Gaudi,Frank Gehry,Le Corbusier,Frank Lloyd Wright', 'MNgvhvE', 'Frank Lloyd Wright', 'Antoni Gaudi,Frank Gehry,Le Corbusier', 'Who was the architect of this house?'),
  (33, 'Lake Geneva,Lake Como,Lake Zurich,Lake Constance', 'UGUP43s', 'Lake Constance', 'Lake Geneva,Lake Como,Lake Zurich', 'Which lake is in this picture?'),
  (34, 'Dog,Cheetah,Cat,Hyena', 'fQf86zn', 'Hyena', 'Dog,Cheetah,Cat', 'Who is looking at you?'),
  (35, 'Hamster,Mouse,Rat,Quokka', 'miLaIWb', 'Quokka', 'Hamster,Mouse,Rat', 'What kind of animal do you see in this awesome image?'),
  (36, 'Sea Lion,Walrus,Shark,Sea Cow', 'JaHt9Dz', 'Sea Cow', 'Sea Lion,Walrus,Shark', 'What kind of animal was captured in this awesome image?'),
  (37, 'Burj Al Arab,Taipei 101,Petronas Towers,Burj Khalifa', 'MLF8jrp', 'Burj Khalifa', 'Burj Al Arab,Taipei 101,Petronas Towers', 'What building was captured in this awesome image?'),
  (38, 'Summer,Spring,Autumn,Winter', 'S7kDnrA', 'Winter', 'Summer,Spring,Autumn', 'What season was captured in this awesome image?'),
  (40, 'England,Sardinia,Malta,Corsica', 'YTULWC8', 'Corsica', 'England,Sardinia,Malta', 'What island was captured in this awesome image?'),
  (41, 'Bear,Hamster,Cat,Wombat', '8vogQaN', 'Wombat', 'Bear,Hamster,Cat', 'What animal was captured in this awesome image?'),
  (42, 'Squirrel,Cotton,Flower,Bird', 'tXfvx', 'Squirrel', 'Cotton,Flower,Bird', 'What object was captured in this awesome image?');;