name: Deploy Project to App Engine

on:
  push:
    branches:
      - main

  # run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:


  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    #needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
        env:
          SP_DS_DRIVER_VAR : ${{ env.SP_DS_DRIVER_VAR }}
          SP_DS_UR: ${{ secrets.SP_DS_UR }}
          SP_DS_UN: ${{ secrets.SP_DS_UN }}
          SP_DS_PW: ${{ secrets.SP_DS_PW }}
          SP_DS_DRIVER: ${{ secrets.SP_DS_DRIVER }}
          SP_DS_PLATFORM: ${{ secrets.SP_DS_PLATFORM }}
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
      - name: Print environment variables
        run: |
          echo "SP_DS_DRIVER: ${{ secrets.SP_DS_DRIVER }}"
          echo "SP_DS_PLATFORM: ${{ secrets.SP_DS_PLATFORM }}"
          echo "SP_DS_DRIVER_VAR: ${{ env.SP_DS_DRIVER_VAR }}"
